---
- hosts: all
  vars:
    project_directory: "{{ ansible_env.HOME }}/hardware_projects/led_lights"
    node_version: 16.6.1
    node_bin: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin"
    cargo_bin: "{{ ansible_env.HOME }}/.cargo/bin"
  tasks:
    #Setting up build chain
  - name: install nvm
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  - name: install npm
    shell: >
      source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }}
    args:
      creates: "{{ node_bin }}/npm"
      executable: /bin/bash
  - name: symbolic link node 
    file: 
      src: "{{ node_bin }}/node" 
      dest: /usr/bin/node
      state: link

  - name: cargo install
    shell: >
      curl https://sh.rustup.rs -sSf | sh -s - -y
    args:
      creates: "{{ cargo_bin }}/cargo"
    register: cargo
  - name: cargo set to nightly
    shell: >
      {{ cargo_bin }}/rustup default nightly


# Install latest version of the files.
  - name: Git checkout
    ansible.builtin.git:
      repo: "https://github.com/jmriesen/LedPiCode.git"
      dest: "{{ project_directory }}"

  - name: Copy led backend service systemd folder
    become: yes
    ansible.builtin.copy:
      src: "{{ project_directory }}/led.service"
      dest: /etc/systemd/system/led.service
      remote_src: yes

  - name: Copy led fronted service systemd folder
    become: yes
    ansible.builtin.copy:
      src: "{{ project_directory }}/led-frontend.service"
      dest: /etc/systemd/system/led-frontend.service
      remote_src: yes


# Backend Setup
  - name: compiling back end
    shell: >
      {{ cargo_bin }}/cargo build --release
    args:
      chdir: "{{ project_directory }}/backend"
 
  - name: starting backend
    become: yes
    service:
      name: led
      state: restarted


# Fronted setup 
  - name: Install packages based on package.json.
    shell: >
      {{ node_bin }}/npm install
    args:
      chdir: "{{ project_directory }}/frontend"

  - name: starting frontend
    become: yes
    service:
      name: led-frontend
      state: restarted
