---
- hosts: all
  tasks:
    #Setting up build chain
  - name: install nvm
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      # symbolic links may be needed for the service keep that in mind.
  - name: install npm
    shell: >
      source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 16.6.1
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.1/bin/npm"
      executable: /bin/bash
  - name: symbolic link node 
    file: 
      src: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.1/bin/node" 
      dest: /usr/bin/node
      state: link

  - name: cargo install
    shell: >
      curl https://sh.rustup.rs -sSf | sh -s - -y
    args:
      creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
    register: cargo

  - name: cargo set to nightly
    shell: >
      {{ ansible_env.HOME }}/.cargo/bin/rustup default nightly
# Install latest version of the files.
  - name: Git checkout
    ansible.builtin.git:
      repo: "https://github.com/jmriesen/LedPiCode.git"
      dest: /home/pi/hardware_projects/led_lights/
    register: git

  - name: Copy led backend service systemd folder
    become: yes
#    when: git.changed
    ansible.builtin.copy:
      src: /home/pi/hardware_projects/led_lights/led.service
      dest: /etc/systemd/system/led.service
      remote_src: yes

  - name: Copy led fronted service systemd folder
    become: yes
#    when: git.changed
    ansible.builtin.copy:
      src: /home/pi/hardware_projects/led_lights/led-frontend.service
      dest: /etc/systemd/system/led-frontend.service
      remote_src: yes
# Backend Setup
  - name: compiling back end
#    when: git.changed
    shell: >
      {{ ansible_env.HOME }}/.cargo/bin/cargo build --release
    args:
      chdir: "{{ ansible_env.HOME }}/hardware_projects/led_lights/backend"
 
  - name: starting backend
    become: yes
#    when: git.changed
    service:
      name: led
      state: restarted
# Fronted setup 
  # - name: Install packages based on package.json.
  #   npm:
  #     ci: yes 
  #     path: "{{ ansible_env.HOME }}/hardware_projects/led_lightss/frontend"
  #     executable: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.1/bin/npm"
  #     state: present
  - name: Install packages based on package.json.
    shell: >
      {{ ansible_env.HOME }}/.nvm/versions/node/v16.6.1/bin/npm install
    args:
      chdir: "{{ ansible_env.HOME }}/hardware_projects/led_lights/frontend"

      #{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.1/bin/npm install
  - name: starting frontend
    become: yes
#    when: git.changed
    service:
      name: led-frontend
      state: restarted
